---
permalink: rhel-install/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, authentication, settings 
summary: 您可以設定OnCommand Workflow Automation 使用Microsoft Active Directory（AD）輕量型目錄存取傳輸協定（LDAP）伺服器進行驗證和授權。 
---
= 設定驗證設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定OnCommand Workflow Automation 使用Microsoft Active Directory（AD）輕量型目錄存取傳輸協定（LDAP）伺服器進行驗證和授權。

您必須在環境中設定Microsoft AD LDAP伺服器。

WFA僅支援Microsoft AD LDAP驗證。您無法使用任何其他LDAP驗證方法、包括Microsoft AD輕量型目錄服務（AD LDS）或Microsoft通用目錄。


NOTE: 在通訊期間、LDAP會以純文字格式傳送使用者名稱和密碼。不過、LDAPS（LDAP安全）通訊是加密且安全的。

.步驟
. 以管理員身分透過網頁瀏覽器登入WFA。
. 將Active Directory群組名稱清單新增至所需的角色。
+

NOTE: 您可以在Active Directory群組視窗中、將AD群組名稱清單新增至所需的角色。

+
xref:task-add-active-directory-group-names.adoc[Active Directory群組視窗]

. 按一下*管理*>* WFA組態*。
. 在「WFA組態」對話方塊中、按一下「*驗證*」索引標籤、然後選取「*啟用Active Directory」核取方塊。
. 在下列欄位中輸入必要資訊：
+
.. 如果您要使用網域使用者的user@domain格式、請在*使用者名稱屬性*欄位中、將sAMAccountName取代為userPrincipalName。
.. 如果您的環境需要唯一值、請編輯必填欄位。


. 按一下「*新增*」以URI格式「LDAP//Active_directory_server_address\[:port\]」、將Active Directory新增至Active Directory伺服器表格
+
LDAP：//NB-T01.example.com[:389]

+
如果您已啟用LDAP over SSL、則可使用下列URI格式：「LDAPS：//active_directory_server_address\[:port\]」

. 提供認證資料以連結LDAP伺服器和基礎DN。
. 測試指定使用者的驗證：
+
.. 輸入使用者名稱和密碼。
.. 按一下*測試驗證*。


+

NOTE: 您必須新增Active Directory群組、才能在WFA中測試特定使用者的驗證。

. 按一下「 * 儲存 * 」。

