---
permalink: rhel-install/task-replace-the-default-workflow-automation-ssl-certificate-linux.html 
sidebar: sidebar 
keywords: replace, default, workflow, automation, ssl, certificate 
summary: 如果憑證已過期、或您想要延長憑證的有效期間、您可以取代預設的Workflow Automation（WFA）SSL憑證。 
---
= 取代預設的Workflow Automation SSL憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果憑證已過期、或您想要延長憑證的有效期間、您可以取代預設的Workflow Automation（WFA）SSL憑證。

您必須擁有已安裝WFA的Linux系統的root權限。

此程序使用預設的WFA安裝路徑。如果您在安裝期間變更了預設位置、則必須使用自訂的WFA安裝路徑。

.步驟
. 以root使用者身分登入WFA主機機器。
. 在Shell提示下、瀏覽至WFA伺服器上的下列目錄：WFA_install_LOWS/WFA/bin
. 停止WFA資料庫和伺服器服務：
+
「/WFA --停止= WFA」

+
「/WFA --stop =資料庫」

. 請從下列位置刪除WFA .keystore檔案：WFA安裝位置/ WFA / Jboss /獨立式/組態/ Keystore。
. 在WFA伺服器上開啟Shell提示字元、然後將目錄變更為下列位置：<OpenJDK_install_location>/bin
. 取得資料庫金鑰：
+
「keytool-keysize 2048-genkey -alias "SSL Keystore」-keyalg ra -keystore「wfa_install_location / wfa/jboss/standaled/configuration / keystore/wfa.keystore」-validity xxxx'

+
XXXX是新憑證有效的天數。

. 出現提示時、請提供密碼（預設或新的）。
+
預設密碼是隨機產生的加密密碼。

+
若要取得並解密預設密碼、請依照知識庫文章中的步驟進行 link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["如何在WFA 5.1.1.0.4上續約自我簽署的憑證"^]

+
若要使用新密碼、請遵循知識庫文章中的步驟 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_update_a_new_password_for_the_keystore_in_WFA["如何在WFA中更新Keystore的新密碼。"^]

. 輸入憑證的必要詳細資料。
. 檢閱顯示的資訊、然後輸入「Yes（是）」。
. 出現下列訊息時、請按* Enter *鍵：輸入<SSL Keystore（<SSL Keystore）>的金鑰密碼（如果與Keystore密碼相同則返回）>。
. 重新啟動WFA服務：
+
「/WFA --start=DB」

+
「/wFA --start=wfa」


