---
settings:
  name: OnCommand Workflow Automation 5.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: 5.1文件OnCommand Workflow Automation
    url: "/index.html"
  - title: 版本資訊
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: 法律聲明
    url: "/reference-legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 版本資訊
      url: reference-releasenotes.html
  - title: 在Linux系統上安裝與設定
    links:
    - title: 安裝OnCommand Workflow Automation 過程中的系統需求
      url: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html
    - title: 管理高可用度
      url: rhel-install/concept-managing-high-availability.html
    - title: 設定OnCommand Workflow Automation 功能
      url: rhel-install/concept-setting-up-oncommand-workflow-automation.html
    - title: 備份OnCommand Workflow Automation 這個資料庫
      url: rhel-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html
    - title: 還原OnCommand Workflow Automation 這個資料庫
      url: rhel-install/concept-restoring-the-wfa-database.html
    - title: 解除安裝OnCommand Workflow Automation
      url: rhel-install/task-uninstall-oncommand-workflow-automation-linux.html
    - title: 疑難排解安裝與組態問題
      url: rhel-install/reference-troubleshooting.html
  - title: 在Windows系統上安裝與設定
    links:
    - title: 安裝OnCommand Workflow Automation 過程中的系統需求
      url: windows-install/reference-system-requirements-for-oncommand-workflow-automation-windows.html
    - title: 在OnCommand Workflow Automation Windows上安裝
      url: windows-install/task-install-workflow-automation-on-windows.html
    - title: 設定OnCommand Workflow Automation 功能
      url: windows-install/concept-setting-up-oncommand-workflow-automation.html
    - title: 備份OnCommand Workflow Automation 這個資料庫
      url: windows-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html
    - title: 還原OnCommand Workflow Automation 這個資料庫
      url: windows-install/concept-restoring-the-wfa-database.html
    - title: 解除安裝OnCommand Workflow Automation
      url: windows-install/task-uninstall-oncommand-workflow-automation.html
    - title: 疑難排解安裝與組態問題
      url: windows-install/reference-troubleshooting.html
  - title: 建置及管理工作流程
    links:
    - title: 管理工作流程
      url: workflows/concept-managing-workflows.html
  - title: 更多資訊
    links:
    - title: NetApp社群
      url: http://community.netapp.com/t5/OnCommand-Storage-Management-Software-Articles-and-Resources/tkb-p/oncommand-storage-management-software-articles-and-resources/label-name/workflow%20automation%20%28wfa%29?labels=workflow+automation+%28wfa%29
    - title: 互通性對照表
      url: http://mysupport.netapp.com/matrix/
