---
permalink: windows-install/task-create-a-certificate-signing-request-for-workflow-automation-windows.html 
sidebar: sidebar 
keywords: workflow, automation, wfa, windows, create, certificate, sign, request 
summary: 您可以在Windows中建立憑證簽署要求（CSR）、以便使用由憑證授權單位（CA）簽署的SSL憑證、而非Workflow Automation（WFA）的預設SSL憑證。 
---
= 建立Workflow Automation的憑證簽署要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在Windows中建立憑證簽署要求（CSR）、以便使用由憑證授權單位（CA）簽署的SSL憑證、而非Workflow Automation（WFA）的預設SSL憑證。

* 您必須在WFA伺服器上擁有Windows管理員權限。
* 您必須更換WFA提供的預設SSL憑證。


此程序使用預設的WFA安裝路徑。如果您在安裝期間變更了預設路徑、則必須使用自訂的WFA安裝路徑。

.步驟
. 以管理使用者身分登入WFA主機機器。
. 在WFA伺服器上開啟命令提示字元、然後將目錄變更為下列位置：+<OpenJDK_install_location>\bin
. 建立CSR：
+
「keytool-certreq -keystore wfa_install_location \wfa\jboss\s獨立 式\configuration \keystore \wfa.keystore -alias "SSL keystore」-file C：\file_name.csr

+
file_name是CSR檔案的名稱。

. 出現提示時、請提供密碼（預設或新的）。
+
預設密碼是隨機產生的加密密碼。

+
若要取得並解密預設密碼、請使用知識庫文章中的步驟 link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["如何在WFA 5.1.1.0.4上續約自我簽署的憑證"^]

. 將file_name.csr檔案傳送至CA以取得簽署的憑證。
+
如需詳細資料、請參閱CA網站。

. 從CA下載鏈結憑證、然後將鏈結憑證匯入至Keystore：「keytool-import -alias "SSL keystore CA certe"-keystore「wfa_install_portion\wfa\jboss\s獨立 式\configuration \keystore \wfa.keystore」-cacerts -file C：\chlune_cert.cer
+
C：\chain /cert.cer是從CA接收的鏈結憑證檔案。檔案必須為X．509格式。

. 匯入您從CA收到的已簽署憑證：
+
「keytool-import-alias "SSL Keystore」-keystore「wfa_install_portion\wfa\jbjboss\s獨立 式\configuration \keystore \wfa.keystore」-file C：\Certificate .cer

+
C：\Certificate .cer是從CA接收的鏈結憑證檔案。

. 啟動下列WFA服務：
+
** NetApp WFA資料庫
** NetApp WFA伺服器



