---
permalink: windows-install/task-install-workflow-automation-on-windows.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, install, windows 
summary: 您可以安裝OnCommand Workflow Automation 功能區（WFA）來建立及自訂儲存工作流程、以自動化在環境中執行的儲存工作。 
---
= 在OnCommand Workflow Automation Windows上安裝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以安裝OnCommand Workflow Automation 功能區（WFA）來建立及自訂儲存工作流程、以自動化在環境中執行的儲存工作。

* 您必須已檢閱安裝先決條件。
+
xref:reference-prerequisites-for-installing-workflow-automation.adoc[安裝Workflow Automation的先決條件]

* 如果您要在先前安裝WFA並解除安裝的系統上安裝WFA、則必須確保該系統上沒有WFA服務。
* 您必須從NetApp支援網站下載WFA安裝程式。
* 如果您要在虛擬機器（VM）上安裝WFA、則VM名稱不得包含底線（_）字元。
* ActiveState ActivePerl是在安裝WFA之前安裝的。
+
此安裝不會影響您在WFA伺服器上安裝的任何其他ActivePerl執行個體。

* 在重新安裝WFA 4.2或更新版本之前、如果您已解除安裝MySQL、則必須刪除MySQL資料目錄。


.步驟
. 使用具有管理權限的帳戶登入Windows。
. 開啟Windows檔案總管、然後瀏覽至安裝檔案所在的目錄。
. 安裝WFA：
+
** 互動式安裝
+
... 以系統管理使用者的身分按一下滑鼠右鍵並執行WFA安裝程式執行檔（.exe）。
... 單擊 * 下一步 * 。
... 輸入預設管理使用者的認證資料、然後按一下*「下一步*」。
+
預設的管理密碼必須符合下列條件：

+
**** 至少八個字元
**** 一個大寫字元
**** 一個小寫字元
**** 一個數字
**** 一個特殊字元
**** 密碼不支援下列特殊字元、導致安裝失敗：
+
「」；<、=&｛caret｝|

+
[NOTE]
====
您必須記下管理使用者的認證資料。

====


... 輸入WFA服務登入的使用者名稱和密碼。對於網域使用者、請以網域\使用者的格式提供使用者名稱。對於本機系統使用者、格式只是使用者名稱。預設使用者名稱為「WFA」。
+
如果不存在WFA安裝程式、則會建立本機使用者。如果存在本機使用者、且輸入的密碼與現有密碼不同、則WFA會更新密碼。

+
[NOTE]
====
確保密碼符合為系統上的本機使用者所設定的密碼原則。如果密碼不符合密碼原則、安裝就會失敗。

====
... 選取WFA組態的連接埠、然後按一下「*下一步*」。
... 輸入網站名稱和公司名稱、然後按「*下一步*」。
+
網站名稱可包含WFA安裝位置、例如、PA匹茲堡。

... 如果您要變更預設安裝位置、請選取您要安裝WFA的位置、然後按一下*「下一步*」。
... 如果您要變更協力廠商產品的預設安裝位置、請選取您要安裝協力廠商產品的位置、然後按一下*「下一步*」。
... 如果您不想變更WFA資料庫的預設位置、請按一下「*下一步*」。
... 按一下「*安裝*」繼續安裝。
... 按一下「*完成*」以完成安裝。
... 選擇下列其中一項動作、確認WFA已成功安裝：
+
**** 透過網頁瀏覽器存取WFA。
**** 使用Windows服務主控台驗證NetApp WFA伺服器服務和NetApp WFA資料庫服務是否正在執行。




** 無聲安裝（從命令提示字元）：
+
 WFA-version_number-build_number.exe /s /v"WFA_ADMIN_USERNAME=wfa_username WFA_ADMIN_PASSWORD=password WFA_ADMIN_CONFIRM_PASSWORD=confirm admin password / WFA_MYSQL_PASS=password CONFIRM_WFA_MYSQL_PASS=confirm MySQL password WFA_INSTALL_SITE=site WFA_INSTALL_ORGANIZATION=organization_name WFA_HTTP_PORT=port WFA_HTTPS_PORT=port INSTALLDIR=install_directory JDKINSTALLDIR=jdk_directory PerlDir=perl_directory MySqlInstallDir=mysql_directory WFA_SERVICE_LOGON_USERNAME=wfa service logon username WFA_SERVICE_LOGON_PASSWORD=wfa service logon user password MYSQL_DATA_DIR= mysql data directory /qr /l*v C:\install.log"
+
* 範例 *

+
WFA-x64-V5.1.0.0.1-B5355278.exe /s /v"wfa_admin_username=admin wfa_admin_password=Company * 123 wfa_admin_confirm_password=Company * 123 wfa_MySQL _pass=MySQL_wfa_install_sport=nb wfa_install_sit=nb wfa_install_Organization=wfa=wfa=wfa_admin_admin_admin_admin_adminfa=wfa=wfa_admin_admin_admin_adminfa=wfa=fa=wfa=_admin_admin_admin_admin_admin_admin_adminfa=fa=fa=yfa=fa=yfa=_admin_admin_admin_admin_admin_admin_admin_password=compa=yfa=yfa=fa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa=yfa="compa

+
[NOTE]
====
WFA不支援/qn選項。

====
+
命令參數如下：

+
[cols="2*"]
|===
| 參數 | 說明 


 a| 
WFA_ADD_USERNAME
 a| 
管理使用者名稱選用參數。如果您未指定值、則此值預設為admin。



 a| 
WFA_admin_password
 a| 
管理使用者密碼必填參數。預設的管理密碼必須符合下列條件：

*** 至少八個字元
*** 一個大寫字元
*** 一個小寫字元
*** 一個數字
*** 一個特殊字元
*** 不允許使用下列字元、並導致密碼輸入失敗：
+
「」；<、=&｛caret｝|





 a| 
WFA_admin_confirm_password
 a| 
管理使用者密碼必填參數



 a| 
WFA_MySQL_pass
 a| 
MySQL使用者密碼必填參數



 a| 
confirm_WFA_MySQL_pass
 a| 
MySQL使用者密碼必填參數



 a| 
WFA_install_ssite
 a| 
安裝WFA的組織單位必要參數



 a| 
WFA_install_Organization_..
 a| 
安裝WFA的組織或公司名稱必填參數



 a| 
WFA_HTTP連接埠
 a| 
HTTP連接埠選用參數。如果您未指定值、則此值預設為80。



 a| 
WFA_HTTPS連接埠
 a| 
HTTPS連接埠選用參數。如果您未指定值、則此值預設為443。



 a| 
安裝
 a| 
安裝目錄路徑選用參數。如果未指定值、路徑預設為「C:\Program Files\NetApp\WFA」。



 a| 
JDKInstallDIR
 a| 
JDK安裝目錄路徑選用參數。如果您未指定值、路徑預設為「C:\Program Files\NetApp\」。



 a| 
PerlDir
 a| 
Perl安裝目錄路徑選用參數。如果未指定值、路徑預設為「C：\Perl64\」。



 a| 
MySqlInstallDir
 a| 
MySQL安裝目錄路徑選用參數。如果未指定值、路徑預設為「C:\Program Files\MySQL\」。



 a| 
WFA服務登入使用者名稱
 a| 
WFA服務登入選用參數的使用者名稱。如果您未指定值、則預設使用者名稱為「WFA」。

對於網域使用者、請以網域\使用者的格式提供使用者名稱。對於本機系統使用者、格式只是使用者名稱。

如果不存在WFA安裝程式、則會建立本機使用者。如果存在本機使用者、且輸入的密碼與現有密碼不同、則WFA會更新密碼。

[NOTE]
====
確保密碼符合為系統上的本機使用者所設定的密碼原則。如果密碼不符合密碼原則、安裝就會失敗。

====


 a| 
WFA_service_logon_password
 a| 
WFA服務登入必要參數的密碼



 a| 
MySQL_data_DIR
 a| 
MySQL Data選用參數的目錄。如果未指定值、路徑預設為「C：\ProgramData\MySQL\MySQLServerData」

僅適用於全新安裝。

|===




*相關資訊*

https://mysupport.netapp.com/site/["NetApp支援"^]
