---
permalink: help/concept-what-return-parameters-are.html 
sidebar: sidebar 
keywords: return, parameter, available, planning, phase, workflow, values, return, debugging, understand 
summary: 傳回參數是工作流程規劃階段之後可用的參數。這些參數傳回的值在偵錯工作流程時很有用。您應該瞭解傳回參數的運作方式、以及哪些參數可做為偵錯工作流程的傳回參數。 
---
= 傳回參數的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
傳回參數是工作流程規劃階段之後可用的參數。這些參數傳回的值在偵錯工作流程時很有用。您應該瞭解傳回參數的運作方式、以及哪些參數可做為偵錯工作流程的傳回參數。

您可以在工作流程中指定一組參數、例如變數屬性、運算式和使用者輸入值、做為傳回參數。在工作流程執行期間、會在規劃階段填入指定參數的值、並開始執行工作流程。然後這些參數的值會以在工作流程的特定執行中計算的方式傳回。如果您想要偵錯工作流程、可以參照參數傳回的值。

當您想要查看這些參數的計算值或選取值時、可以在工作流程中指定必要的傳回參數。例如、使用資源選取邏輯來選取工作流程中的集合體時、您可以指定「Aggregate」作為傳回參數、以便查看在工作流程規劃期間選取的集合體。

在參考偵錯工作流程的傳回參數值之前、您應該確認工作流程的執行已完成。每個工作流程執行都會設定傳回參數值。如果您在工作流程執行數次之後新增傳回參數、則該參數的值僅可在新增參數之後執行。



== 可做為傳回參數的參數

[cols="2*"]
|===
| 傳回參數 | 範例 


 a| 
純量的變數屬性
 a| 
volume1.name,`是"'volume name'"變數的屬性



 a| 
常量
 a| 
MAX_Volume大小



 a| 
使用者輸入
 a| 
$clustername



 a| 
包含可變屬性、常量和使用者輸入的VEL運算式
 a| 
volume1.name+'-'+$clusterName



 a| 
命令在執行期間新增的傳回參數
 a| 
當您在PowerShell命令中使用下列命令行時、會新增'$volueUUUUUID'參數作為傳回參數：「Add-WfaWorkFlowParameter -Name「Volume UUID」-Value「'12345'」-AddAsReturnParedarumer$true。

|===


== 預先定義工作流程中的傳回參數範例

如果您想要瞭解如何指定傳回參數、可以在Designer中開啟下列預先定義的工作流程、然後檢閱指定的傳回參數：

* 在vFiler中建立NFS Volume
* 在VFiler中建立Qtree CIFS共用
* 建立叢集Data ONTAP 式的「叢集式功能」CIFS共用區

