---
permalink: help/concept-how-entity-versioning-works.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, wfa, entity, command, version, manage, change 
summary: 諸如命令和工作流程等支援功能（WFA）實體均已版本化。OnCommand Workflow Automation您可以使用版本編號輕鬆管理WFA實體的變更。 
---
= 實體版本管理的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
諸如命令和工作流程等支援功能（WFA）實體均已版本化。OnCommand Workflow Automation您可以使用版本編號輕鬆管理WFA實體的變更。

每個WFA實體都會以「major.menter.reversion」格式包含一個版本編號、例如1.1.20。版本號碼的每個部分最多可包含三位數。

在修改WFA實體的版本編號之前、您必須瞭解下列規則：

* 版本號碼無法從目前版本變更為舊版。
* 版本的每個部分都必須是0到999之間的數字。
* 根據預設、新的WFA實體版本為1.1.0。
* 複製或使用*另存新檔*來儲存實體複本時、會保留實體的版本編號。
* 一個實體的多個版本無法存在於WFA安裝中。


當您更新WFA實體版本時、其直接父實體的版本會自動更新。例如、更新*建立磁碟區*命令的版本會更新*建立NFS磁碟區*工作流程、因為*建立NFS磁碟區*工作流程是*建立磁碟區*命令的直接父實體。自動更新至版本的套用方式如下：

* 修改實體的主要版本會更新其直接父實體的次要版本。
* 修改實體的次要版本會更新其直接父實體的修訂版。
* 修改實體的修訂版不會更新其直接父實體版本的任何部分。


下表列出WFA實體及其直接父實體：

[cols="2*"]
|===
| 實體 | 直接父實體 


 a| 
快取查詢
 a| 
* 資料來源類型




 a| 
範本
 a| 
* 工作流程




 a| 
功能
 a| 
* 工作流程
* 範本



NOTE: 如果某個函數包含特殊或混合大小寫字元、則其直接父實體的版本可能不會更新。



 a| 
字典
 a| 
* 範本
* 篩選器
* 快取查詢
* 命令
* 使用指令碼方法的資料來源類型




 a| 
命令
 a| 
* 工作流程




 a| 
篩選器
 a| 
* 搜尋工具
* 工作流程




 a| 
搜尋工具
 a| 
* 工作流程




 a| 
資料來源類型
 a| 
無



 a| 
工作流程
 a| 
無

|===
您可以使用版本編號的部分或完整版本編號、在WFA中搜尋實體。

如果您刪除父實體、子實體將會保留、其版本不會更新以供刪除。



== 匯入實體時版本管理的運作方式

如果您從Workflow Automation 2.2之前的版本匯入實體、則根據預設、這些實體的版本會以1.1.0版本進行版本控制。如果匯入的實體已存在於WFA伺服器中、則現有實體會被匯入的實體覆寫。

以下是在匯入期間WFA實體的潛在變更：

* 實體升級
+
這些實體將被更新版本所取代。

* 實體復原
+
這些實體會以舊版取代。

+

NOTE: 當您執行實體的復原時、其直接父實體的版本會更新。

* 匯入新的實體



NOTE: 您無法選擇性地從「.Dar」檔案匯入實體。

如果匯入較新版本的實體、則會更新其直接父實體的版本。

如果匯入的父實體有多個子實體、則只有子實體的最高變更度（主要、次要或修訂）會套用至父實體。下列範例說明此規則的運作方式：

* 對於匯入的父實體、如果有一個子實體發生小變更、另一個子實體發生修訂變更、則該小變更會套用至父實體。
+
父版本的修訂部分會遞增。

* 對於匯入的父實體、如果有一個子實體發生重大變更、另一個子實體發生小變更、則主要變更會套用至父實體。
+
父版本的次要部分會遞增。





== 匯入子實體版本如何影響父實體版本的範例

請考慮WFA中的下列工作流程：「Create Volume and export Using NFS - Custom」1.1.0。

工作流程中包含的現有命令如下：

* 「Create Export Policy - Custom' 1.0.0
* 「Create Volume - Custom」（建立Volume -自訂）1.0.0


要匯入的.Dar檔案中包含下列命令：

* 「Create Export Policy - Custom' 1.1.0」（建立匯出原則-自訂）
* 「Create Volume - Custom」（建立Volume -自訂）2.0.0


匯入此.Dar檔案時、「Create Volume and exporting Using NFS - Custom」（使用NFS建立Volume並匯出自訂）工作流程的次要版本會遞增至1.1.0。
