---
permalink: help/reference-edit-active-directory-group-dialog-box.html 
sidebar: sidebar 
keywords: edit, active directory, dialog box, enable, view, modify, oncommand, workflow, automation, group 
summary: 「編輯Active Directory群組」對話方塊可讓您檢視及修改OnCommand Workflow Automation 「Active Directory群組」設定。 
---
= 「編輯Active Directory群組」對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「編輯Active Directory群組」對話方塊可讓您檢視及修改OnCommand Workflow Automation 「Active Directory群組」設定。

視Active Directory群組權限和角色而定、您可能無法存取Active Directory群組視窗。不過、您可以選取*設定*來編輯Active Directory群組的設定、然後在*管理*下按一下* Active Directory群組*。


NOTE: 可供您編輯的欄位取決於Active Directory群組權限。

* *群組名稱*
+
顯示Active Directory群組的群組名稱。

* *角色*
+
顯示使用者帳戶的指派角色。

+
顯示指派給Active Directory群組的下列其中一個群組角色：

+
** *來賓*
+
此群組只能檢視工作流程執行狀態、或收到工作流程執行狀態變更通知。

** *營運者*
+
此群組可預覽及執行提供群組存取權的工作流程。

** *核准人*
+
此群組可預覽、執行、核准及拒絕提供群組存取權的工作流程。

+

NOTE: 您必須提供核准者的電子郵件ID、以及要通知核准者的工作流程狀態。如果有多位核准者、您可以在*電子郵件*欄位中提供群組電子郵件ID。

** *架構設計師*
+
此群組擁有建立工作流程的完整存取權、但受到限制、無法修改全域WFA伺服器設定。

** *管理*
+
此群組可完整存取WFA伺服器。

+

NOTE: 您必須至少設定一個管理群組。



* *電子郵件*
+
指定在選取「*通知開啟*」選項時、要傳送通知的Active Directory群組電子郵件。

* *通知於*
+
可讓您選擇在該Active Directory群組觸發的工作流程執行期間、何時應以電子郵件通知Active Directory群組。您可以選擇下列選項的任意組合：

+
** 工作流程執行已開始：工作流程執行開始時通知使用者。
** 工作流程執行失敗/部分成功：在工作流程執行失敗或工作流程成功執行時通知使用者、即使有一或多個步驟失敗。
+
執行完成的原因是失敗的步驟已設定為即使步驟失敗、仍可繼續執行工作流程。

** 工作流程執行成功完成：工作流程執行成功時通知使用者。
** 工作流程執行等待核准：視WFA組態設定而定、如果工作流程執行等待操作員或架構設計師使用者核准、則會通知使用者。






== 命令按鈕

* *儲存*
+
儲存組態設定並關閉對話方塊。

* *取消*
+
取消變更（如果有）、然後關閉對話方塊。


