---
permalink: help/reference-edit-data-source-dialog-box.html 
sidebar: sidebar 
keywords: edit, data, source, dialog box, enable, modify, existing 
summary: 「編輯資料來源」對話方塊可讓您修改現有的資料來源。 
---
= 編輯資料來源對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「編輯資料來源」對話方塊可讓您修改現有的資料來源。



== 資料來源組態內容

* *名稱*
+
可讓您修改資料來源的名稱。

* *資料來源類型*
+
顯示資料來源的資料來源類型。您無法修改此欄位。

* *主機名稱*
+
可讓您指定資料來源的主機名稱或IP位址（IPv4或IPv6）。

+

NOTE: 不支援IPv6位址的支援來源類型。Active IQ Unified Manager

* *連接埠*
+
顯示所選資料來源類型的相關連接埠號碼（如果有）。您可以變更資料來源的預設連接埠號碼。

* *方案*
+
顯示與所選資料來源類型相關的配置、例如Unified Manager - 6.0（MySQL）的_cm_storage。

+
您無法修改此屬性。

* *使用者名稱*
+
顯示所選資料來源類型的相關使用者名稱（若有）。

+
您必須為此資料來源指定適當的使用者名稱、才能覆寫預設的使用者名稱：

+
** 對於6.0之前的Unified Manager版本、您必須輸入在執行ocsetup時、用來覆寫預設認證的使用者名稱。
** 對於Unified Manager 6.0及更新版本、您必須輸入您在Unified Manager伺服器上建立的資料庫使用者帳戶使用者名稱。
** 對於Performance Advisor、您必須輸入Active IQ Unified Manager 角色最低為GlobalRead的使用者名稱。


* *密碼*
+
可讓您指定所選資料來源類型的密碼。

+
您必須指定密碼、以覆寫此資料來源使用者名稱的預設密碼：

+
** 對於6.0之前的Unified Manager版本、您必須輸入密碼、以便在執行ocsetup時覆寫預設認證。
** 對於Unified Manager 6.0及更新版本、您必須輸入您在伺服器上建立的資料庫使用者帳戶密碼。
** 對於Performance Advisor、您必須輸入Unified Manager使用者的密碼、且其角色下限為GlobalRead。


* *資料庫*
+
顯示所選資料來源類型的相關資料庫名稱（若有）。

* *時間間隔（分鐘）*
+
可讓您按一下值、然後使用向上和向下箭頭選取時間間隔（以分鐘為單位）。

+

NOTE: 如果時間間隔設為零（0）、則會停用自動取樣。

+
資料取樣的預設時間間隔為：

+
** 指令碼型資料來源類型：1440（效能與虛電路）
** SQL型資料來源類型：30（cm_storage、storage和cm_Performance）


* *請參閱設定說明指南*
+
開啟「設定指示指南」對話方塊、其中概述設定資料來源的步驟。





== 命令按鈕

* *重設方案*
+
開啟「重設方案」確認對話方塊。此對話方塊可讓您重設所選配置的快取儲存區、此儲存區會在下一次擷取資料時發生。

+

IMPORTANT: 重設程序會刪除所有快取資料、包括所有資料表。整個快取是從下一次擷取資料開始建置的。

* *儲存*
+
儲存組態設定並關閉對話方塊。

* *取消*
+
取消變更（如果有）、然後關閉對話方塊。


