---
permalink: help/reference-resource-selection-dialog-box.html 
sidebar: sidebar 
keywords: resource, selection, dialog box, enable, search, map, command 
summary: 「資源選取」對話方塊可讓您搜尋資源、並將資源對應至命令。 
---
= 資源選取對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「資源選取」對話方塊可讓您搜尋資源、並將資源對應至命令。

* 選取<dictionary object> by（依據索引標籤）
* 進階索引標籤




== 選取<dictionary object> by（依據索引標籤）

此索引標籤可讓您將搜尋器或篩選器指定為搜尋條件、並輸入所選搜尋條件的屬性。您也可以將選取的篩選器儲存為搜尋器。

* *定義篩選規則*
+
可讓您定義一組用於字典項目資源的規則、例如vFiler單元、集合體和虛擬機器。

+
篩選規則可以包含一或多個規則群組。

+
規則包含一個字典項目屬性、運算子和一個值。屬性也可以包含其參照的屬性。例如、您可以指定集合體規則、如下所示：列出名稱開頭為字串「aggr"的所有集合體、可用大小大於5 GB。群組中的第一條規則是屬性「'name'」、運算子「'-tar-with」和值「'aggr'」。同一群組的第二項規則是屬性「可用的_size_MB"、運算子為「'>'」、值為「'5000」。

+
如果您選擇了查找器，則會禁用*定義篩選規則*選項。

+
您可以按一下*重設*按鈕來清除指定的值。

* *按一種資源的自然金鑰來選取*
+
可讓您根據資源的自然金鑰來選取資源。

* *搜尋器*
+
可讓您從清單中選取尋找工具。*預設會選取「無」*。

+
篩選器會顯示在搜尋器清單下方。如果您已選取尋找器、則無法選取篩選器。

* *參數*
+
可讓您輸入所選尋找器或篩選器的值。您必須輸入所有必要的值、才能完成搜尋條件。

* *命令按鈕*
+
** *另存為Finder *
+
將選取的篩選器儲存為搜尋器。

** *測試*
+
可讓您在參數區域中指定值之前、先測試所選篩選器的參數。

** *確定*
+
儲存組態設定並關閉對話方塊。

** *取消*
+
取消變更（如果有）、然後關閉對話方塊。







== 進階索引標籤

此索引標籤可讓您指定何時應執行搜尋、並可讓您排序資源屬性和資源屬性的狀態。

* *永遠執行此搜尋*
+
執行命令時、不受任何限制地執行搜尋。

* *僅當下列運算式評估為true*時、才執行搜尋
+
只有當方塊中指定的選用屬性值為「true」時、才會執行搜尋。您可以使用MVFlex運算式語言（MVEL）語法來指定選用屬性。

* *排序表*
+
顯示在「*選取<dictionary object> by *」索引標籤中選取之篩選器的屬性和排序順序。排序順序對於資源選擇而言相當重要、例如、如果您選取降序作為集合體的排序順序、則會選取最大「可用空間」的集合體做為資源。若要變更屬性的排序順序、您可以按一下屬性的狀態欄、然後從清單中選取所需的排序順序。

* *命令按鈕*
+
** *上*
+
將「排序」表格中選取的項目上移一列。

** *關機*
+
在「排序」表格中、將選取的項目下移一列。




