---
permalink: help/reference-clone-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: clone, command, definition, dialog box, enable, copy, edit 
summary: Clone Command Definition（Clone命令定義）對話方塊可讓您複製命令並編輯複製的命令。 
---
= Clone Command Definition（克隆命令定義）對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Clone Command Definition（Clone命令定義）對話方塊可讓您複製命令並編輯複製的命令。

* 內容索引標籤
* 程式碼索引標籤
* 「參數定義」標籤
* 「參數對應」索引標籤
* 「保留」標籤
* 驗證索引標籤




== 內容索引標籤

可讓您編輯複製命令的內容、例如名稱、說明和實體版本。

* *名稱*
+
可讓您編輯複製的命令名稱。根據預設、您選取要複製的命令名稱會做為複本名稱、並附加「`- copy」。

* *實體版本*
+
可讓您以「major.mine.re版本」格式編輯命令的版本編號、例如1.1.0。

* *說明*
+
可讓您編輯命令說明。

* *字串表示*
+
可讓您使用MVFlex運算式語言（MVEL）語法、為命令指定字串表示。您必須指定字串表示法、才能儲存命令。

* *超時（s）*
+
可讓您指定命令的逾時值（以秒為單位）。預設值為600秒。

* *命令類型*
+
可讓您指定命令的執行類型。

+
** *標準執行*
+
讓命令無需等待任何時間即可執行。預設會選取標準執行。

** *等待條件*
+
可讓您指定命令在執行之前必須等待的時間（以秒為單位）。預設值為60秒。



* *最低軟體版本*
+
指定命令運作所需的軟體最低版本。例如、軟體可以是叢集Data ONTAP 式的VMware vCenter 8.2.0和vCenter 6.0。這些版本會以以逗號分隔的值顯示。

* *保留原始命令的保留與驗證指令碼*
+
可讓您保留原本針對要複製的命令所指定的保留與驗證指令碼。





== 程式碼索引標籤

可讓您編輯命令的程式碼。

* *探索參數*
+
將PowerShell程式碼中定義的參數複製到「參數定義」表格和「參數對應」表格。





== 「參數定義」標籤

顯示您在「代碼」標籤中輸入的代碼中定義的參數。

* *名稱*
+
顯示參數的名稱。

* *說明*
+
顯示參數的說明。

* *必填*
+
顯示必要參數的選取核取方塊。

* *類型*
+
顯示參數的類型、例如字串或列舉。

* *值*
+
顯示為參數設定的值。

* *新增參數*
+
如果所選的指令碼語言是Perl、則可讓您在命令中新增參數。

* *移除參數*
+
如果所選的指令碼語言是Perl、則可讓您從命令中移除參數。





== 「參數對應」索引標籤

可讓您將參數對應至字典物件、並指定屬性和物件名稱。

* *名稱*
+
顯示參數的名稱。

* *類型*
+
可讓您選取參數的字典物件。

* *屬性*
+
可讓您指定必要的屬性。您可以選取屬性（若有）、或輸入屬性名稱。

* *物件名稱*
+
可讓您指定字典物件的名稱。





== 「保留」標籤

可讓您保留命令所需的資源。

* *保留指令碼*
+
可讓您輸入SQL查詢、以保留命令所需的資源。這有助於確保所需資源在排程的工作流程執行期間可用。

* *保留代表*
+
可讓您使用VEL語法來指定保留的字串表示。字串表示法用於在「保留」視窗中顯示保留的詳細資料。





== 驗證索引標籤

可讓您驗證保留區、並在執行命令後移除保留區。

* *驗證腳本*
+
可讓您輸入SQL查詢、以驗證保留指令碼所保留的資源使用量。驗證指令碼也會驗證WFA快取是否已更新、並在擷取快取後移除保留。

* *測試驗證*
+
開啟「驗證」對話方塊、可讓您測試驗證指令碼的參數。





== 命令按鈕

* *測試*
+
在<ScriptLanguage（腳本語言）>對話方塊中開啟Testing Command <CommandName>（測試命令<CommandName>）、以便測試命令。

* *儲存*
+
儲存命令並關閉對話方塊。

* *取消*
+
取消變更（如果有）、然後關閉對話方塊。


