---
permalink: help/reference-edit-variable-dialog-box.html 
sidebar: sidebar 
keywords: edit, variable, dialog box, enable, user, input, attributes, workflow 
summary: 編輯變數：對話方塊可讓您編輯工作流程的使用者輸入屬性。 
---
= 編輯變數對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
編輯變數：對話方塊可讓您編輯工作流程的使用者輸入屬性。



== 屬性

* *變數名稱*
+
可讓您編輯使用者輸入的名稱。重新命名使用者輸入會更新工作流程中使用者輸入的所有參考資料。

* *顯示名稱*
+
可讓您指定或編輯使用者輸入的顯示名稱。如果您已建立名稱相似的使用者輸入屬性、則可以指定唯一的顯示名稱。

* *說明*
+
可讓您指定或編輯使用者輸入的說明。當您執行或預覽工作流程時、說明會以工具提示的形式出現。

* *類型*
+
可讓您選取使用者輸入類型。欄位或對話方塊連結會根據選取的選項顯示。可用選項包括：

+
** 字串：可讓您在regex欄位中輸入有效值的規則運算式、例如A*。
** Number：可讓您在範圍欄位中輸入數值範圍、例如1到15。
** 列舉：可讓您在「列舉值」欄位中輸入封閉的值清單。
** 查詢：可讓您輸入簡單的SQL查詢來取得結果。
+
使用者只能從結果的第一欄選取值。

** 查詢（多重選取）：可讓您輸入SQL查詢、以取得值清單。
+
使用者可以在執行工作流程時選取單一值或多個值、例如、您可以選取一個磁碟區、多個磁碟區或磁碟區與其共用及匯出。

+
您可以從結果中顯示的任何欄中選取值。選取一列會從所選列的所有欄中選取值。

** 布林值：可讓您在「使用者輸入」對話方塊中顯示核取方塊。
** 表：可讓您指定表格的欄標題、以便在執行工作流程期間輸入多個值、例如可用來指定節點名稱和連接埠名稱清單的表格。
+
您也可以設定欄使用者輸入的類型、以及與欄使用者輸入相關聯的內容。會根據選取的使用者輸入類型顯示對話方塊。可用選項包括：

+
*** 字串：可讓您在regex欄位中輸入有效值的規則運算式、例如A*。
*** Number：可讓您在範圍欄位中輸入數值範圍、例如1到15。
*** 列舉：可讓您在「列舉值」欄位中輸入封閉的值清單。
*** 查詢：可讓您輸入簡單的SQL查詢來取得結果。
+
使用者只能從結果的第一欄選取值。資料表使用者輸入欄內的查詢無法參照查詢內的其他使用者輸入。

*** 布林值：可讓您從下拉式清單中選取「'true'」或「'假'」作為布林值。


** 密碼：可讓您加密使用者輸入的密碼。
+
加密後、密碼會在WFA應用程式和記錄檔中以星號字元順序顯示。

** dictionary：可讓您新增所選dictionary項目的表格資料。
+
dictionary項目屬性會選取要傳回的屬性。您可以在執行工作流程時選取單一值或多個值。例如、您可以選取一個磁碟區、多個磁碟區或磁碟區與其共用區和匯出區。預設會選取單一值。您也可以選取篩選規則。規則包含一個字典項目屬性、運算子和一個值。屬性也可以包含其參照的屬性。例如、您可以指定集合體規則、列出名稱開頭為字串「aggr"的所有集合體、可用大小大於5 GB。群組中的第一個規則是屬性「name」、運算子「sharts with」、以及值kaggr。同一群組的第二個規則是屬性「可用的_size_MB」、運算子為「>」、值為5000。



* *鎖定值*
+
可讓您指定是否允許使用者輸入查詢傳回值以外的值。選取此核取方塊不允許使用者提供值、只能選取查詢傳回的值。此選項適用於Enum和Query類型選項。

* *預設值*
+
可讓您設定使用者輸入的預設值。

* *必填*
+
可讓您指定執行工作流程時是否必須輸入使用者資訊。





== 群組

* *群組名稱*
+
可讓您將相關的使用者輸入屬性分組在一起。使用者輸入屬性會以您在預覽或執行工作流程時所定義的群組顯示。例如、您可以將與Volume Details相關的使用者輸入屬性分組在一起。

* *依預設展開群組*
+
可讓您將群組中指定的所有使用者輸入屬性顯示為展開清單。如果未選取此核取方塊、則使用者輸入群組會摺疊顯示。





== 相依性

可讓您根據輸入給其他使用者輸入的值來啟用使用者輸入。例如、在設定NAS傳輸協定的工作流程中、您可以將傳輸協定所需的使用者輸入指定為「NFS」、以啟用「讀寫主機清單」使用者輸入或「CIFS」來啟用「CIFS ACL組態」。

* *選擇使用者輸入內容以視*而定
+
可讓您選取所需的使用者輸入、以啟用「變數名稱」欄位中顯示的使用者輸入。

* *適用值（以英文分隔）*
+
可讓您指定條件式使用者輸入的值、以啟用「變數名稱」欄位中顯示的使用者輸入。


