---
permalink: help/reference-edit-workflow-window.html 
sidebar: sidebar 
keywords: workflow, window, display, select, associated, commands, parameters, blue boxes, columns, arranged, sequential, order, execution, left, right, variables, objects, gray boxes 
summary: 「Workflow <Workflow name>」（工作流程名稱）視窗會顯示所選的工作流程及其相關的命令和參數。與工作流程相關的命令會以藍色方塊的形式顯示在欄中、這些欄會依執行順序排列、從左到右。每個命令的變數和物件會在命令下方顯示為灰色方塊。 
---
= 工作流程<工作流程名稱>視窗
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「Workflow <Workflow name>」（工作流程名稱）視窗會顯示所選的工作流程及其相關的命令和參數。與工作流程相關的命令會以藍色方塊的形式顯示在欄中、這些欄會依執行順序排列、從左到右。每個命令的變數和物件會在命令下方顯示為灰色方塊。



== 工作流程索引標籤

「工作流程」索引標籤可讓您選取及使用子工作流程和命令、並自訂顯示名稱。

* *可用步驟*
+
提供可新增至工作流程的可用子工作流程和命令清單。

+
您可以在文字方塊中使用名稱、配置和最小軟體版本做為搜尋字串、來搜尋子工作流程或命令。

+
您可以重新排列命令順序、自訂工作流程顯示。若要重新排列命令、您可以依所需順序拖放命令。按兩下命令可將該命令移至清單結尾。您可以在藍色方塊中按兩下命令的顯示名稱、以修改顯示名稱。您可以將游標移到藍色方塊上方、然後按一下右上角的「X」來刪除命令。

+
您可以按一下列號、在列上執行各種功能。

+
** *插入一列*
+
在工作流程中所選列的上方或下方插入新列。

** *複製列*
+
從工作流程複製選取的列、並將其儲存至剪貼簿。複製列時、會複製該列的重複詳細資料集。

** *重複列*
+
開啟「列重複詳細資料」對話方塊、可讓您指定重複類型。

** *新增條件*
+
開啟列<列編號>的條件對話方塊、可讓您選取條件。選取的條件適用於該列中的所有命令。只有符合所選條件時、才會執行該列中的所有命令。

** *移除列*
+
從工作流程中刪除選取的列。



* *貼上資料列*
+
將複製的列貼在所選列的上方或下方。選取「複製」列功能後、即可使用此選項。





== 詳細資料索引標籤

「詳細資料」索引標籤可讓您提供工作流程的一般資訊。

* *工作流程名稱*
+
可讓您使用英數字元字串來指定工作流程名稱。

* *實體版本*
+
可讓您以「major.major.more.reversion」格式輸入工作流程的版本編號、例如1.1.0。

* *類別*
+
顯示工作流程的相關類別。您可以從「類別」視窗將工作流程指派給類別。

* *工作流程說明*
+
可讓您輸入工作流程的說明。您可以在欄位中按一下以開啟「編輯說明」對話方塊。

* *準備正式作業*
+
可讓您將工作流程標示為已準備好供正式作業使用、以便在「工作流程」視窗中執行和列出工作流程。

* *考慮保留的要素*
+
可讓您針對工作流程使用保留功能、在所選資源可供工作流程使用時、直到您設定的保留到期期間為止。保留功能可讓您在資源選取期間排除其他工作流程保留的資源。

+

NOTE: 如果您要求篩選器只搜尋持續快取的內容、而不考慮其他工作流程所設定的保留、則不得選取此核取方塊。

* *啟用元素存在驗證*
+
可讓您驗證元素是否存在、並避免在執行工作流程期間發生某些動作失敗。例如、您可以避免在陣列中建立與現有磁碟區名稱相同的新磁碟區。

* *最低軟體版本*
+
指定執行工作流程所需的軟體版本下限。例如、軟體可以是叢集Data ONTAP 式的VMware vCenter 8.2.0和vCenter 6.0。這些版本會以以逗號分隔的值顯示。





== 使用者輸入標籤

使用者輸入索引標籤可讓您檢視及編輯在定義工作流程物件及建立使用者輸入時所建立的使用者輸入屬性。當您預覽或執行工作流程時、會填入使用者輸入屬性的值。

您可以按兩下您要編輯的使用者輸入、這會開啟「Edit Variable：」（編輯變數：）對話方塊、讓您編輯使用者輸入。

您可以重新排列欄順序來自訂表格顯示。若要重新排列欄位、您可以依所需順序拖放欄位。不過、您無法隱藏或刪除這些欄。

* *名稱*
+
顯示使用者輸入屬性的名稱。

* *顯示名稱*
+
顯示顯示給工作流程使用者的名稱。

* *類型*
+
顯示使用者輸入類型、例如字串、查詢、布林、表格、 或密碼。

* *值*
+
顯示使用者輸入的允許值、例如數字範圍和字串的規則運算式。

* *預設值*
+
顯示使用者輸入的預設值。

* *輸入相依性*
+
顯示清單中的另一個使用者輸入、該輸入會提供所選使用者輸入的值。

* *群組*
+
顯示使用者輸入屬性的群組名稱。

* *必填*
+
顯示使用者輸入的狀態。如果核取方塊顯示為已選取、則執行工作流程時、使用者輸入屬性為必填項目。

* *命令按鈕*
+
** *上*
+
將表格中選取的項目上移一列。

** *關機*
+
將所選項目下移表格中的一列。







== 「常量」標籤

「常量」索引標籤可讓您定義可在工作流程中多次使用的常量值。您可以將下列項目指定為常量值：

* 數字
* 字串
* VEL運算式
* 功能
* 使用者輸入
* 變數


您可以透過排序每個欄、以及重新排列欄順序、來自訂表格顯示。

* *名稱*
+
顯示常量的名稱。

* *說明*
+
可讓您指定常量的說明。

* * 價值 *
+
可讓您指定常量的值。

* *命令按鈕*
+
** *新增*
+
在「常量」表格中新增一列。

** *移除*
+
從「常量」表格中刪除選取的列。



+
您也可以在常量上按一下滑鼠右鍵、以使用複製與貼上功能。





== 「傳回參數」索引標籤

「傳回參數」索引標籤可讓您定義並提供可從「監控」視窗或網路服務檢視之工作流程傳回參數的說明。

* *參數值*
+
可讓您指定參數值。

* *參數名稱*
+
可讓您指定參數名稱。

* *說明*
+
可讓您指定所選參數的說明。

* *命令按鈕*
+
** *新增列*
+
在「傳回參數」表格中新增一列。

** *移除列*
+
從「傳回參數」表中刪除選取的列。







== 說明內容索引標籤

「說明內容」索引標籤可讓您新增、檢視及移除工作流程的「說明」內容。工作流程說明內容提供儲存操作員工作流程的相關資訊。



== 進階索引標籤

「進階」索引標籤可讓您設定自訂URI路徑、以便透過API呼叫執行工作流程。URI路徑中的每個區段都可以是字串、或是工作流程使用者輸入的有效名稱、以方括弧括住。

例如/DevOps /\｛ProjectName｝/ Clone。工作流程可呼叫_https：_//WFA-Server:HTTPS連接埠/REST /DevOps /工程1/clone/jobs。



== 命令按鈕

命令按鈕位於工作流程視窗底部。您也可以從視窗中的滑鼠右鍵功能表存取這些命令。

* *預覽*
+
開啟「預覽工作流程」對話方塊、可讓您指定使用者輸入屬性。

* *另存新檔*
+
可讓您以新名稱儲存工作流程。

* *儲存*
+
儲存組態設定。


