---
permalink: workflows/concept-how-you-define-user-input.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, user, input, data, options, available, during, execution, define, parameters, enhance, flexibility, usability 
summary: 功能（WFA）使用者輸入是執行工作流程時可用的資料輸入選項。OnCommand Workflow Automation您必須為工作流程定義使用者輸入參數、以增強工作流程的靈活度與使用性。 
---
= 如何定義使用者輸入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
功能（WFA）使用者輸入是執行工作流程時可用的資料輸入選項。OnCommand Workflow Automation您必須為工作流程定義使用者輸入參數、以增強工作流程的靈活度與使用性。

使用者輸入會顯示為輸入欄位、可在預覽或執行工作流程時填寫相關資料。在工作流程中指定命令詳細資料時、您可以先以美元符號（$）預先固定標籤或變數、以建立使用者輸入欄位。例如、$Volume Name會建立Volume Name使用者輸入欄位。WFA會自動將您建立的使用者輸入標籤填入「Workflow <工作流程名稱>」視窗中的「使用者輸入」標籤。您也可以修改使用者輸入屬性（例如類型、顯示名稱、預設值和驗證值）、以定義使用者輸入類型並自訂輸入欄位。



== 使用者輸入類型選項

* *字串*
+
您可以將規則運算式用於有效值、例如A*。

+
像是0d和0f等字串、會被視為類似於0 d的數字、以雙精度型的0進行評估。

* *號碼*
+
您可以定義可選取的數值範圍、例如1至15。

* * Enum*
+
您可以建立列舉值、以便在使用enum類型填入使用者輸入欄位時選取。您可以選擇性地鎖定已建立的列舉值、以確保只選取您已建立的值供使用者輸入。

* *查詢*
+
當您想要從WFA快取中可用的值中選取使用者輸入時、可以選取查詢類型。例如、您可以使用下列查詢、以WFA快取中的IP位址和名稱值自動填入使用者輸入欄位： *「選擇IP、儲存陣列名稱」*您可以選擇鎖定查詢擷取的值、以便只選取查詢所重試的結果。

* *查詢（多重選取）*
+
查詢（多重選取）類型與查詢類型類似、可在執行工作流程期間選取多個值。例如、使用者可以選取多個磁碟區或一個磁碟區、以及其共用和匯出。您可以允許使用者選取多列、或將選取範圍限制在單一列。選取一列會從所選列的所有欄中選取值。



使用查詢（多重選取）類型的使用者輸入時、您可以使用下列功能：

* GetSiz..
* getValueAt
* getValueAt2D
* getValueFrom2DByRowKey
+
** *布林*
+
您可以使用布林類型在使用者輸入對話方塊中顯示核取方塊。您必須使用布林類型來輸入「'true'」和「'fals'」作為可能值的使用者輸入。

** *表*
+
您可以使用使用者輸入的表格類型來指定表格的欄標題、以便在工作流程執行期間輸入多個值。例如、可用來指定節點名稱和連接埠名稱清單的表格。您也可以為欄標題指定下列其中一種使用者輸入類型、以驗證在執行時間內輸入的值：



* 字串
* 數量
* 列舉
* 布林值
* 查詢「tring」是欄標題的預設使用者輸入類型。您必須按兩下類型欄、才能指定不同的使用者輸入類型。
+
您可以在Designer中開啟「建立SnapMirror原則和規則」工作流程、以瞭解如何在「『napMirrorPolicyRule』」使用者輸入中使用使用者輸入類型。

+
使用表格類型的使用者輸入時、您可以使用下列功能：

* GetSiz..
* getValueAt
* getValueAt2D
* getValueFrom2DByRowKey您可以在Designer中開啟*「建立並設定具有無限Volume *的儲存虛擬機器」工作流程、以查看表格類型的使用方式。
+
** *密碼*
+
您可以將密碼類型用於輸入密碼的使用者輸入。使用者輸入的密碼會加密、並在WFA應用程式和記錄檔中以星號字元順序顯示。您可以使用下列功能來解密密碼、然後由命令使用：



* 對於Perl命令：WFAUtil：：getWfaxInputPassword（$password）
* 對於PowerShell命令：Get-WfaxInputPassword -EncryptedPassword $password
+
在此、$password是WFA傳送至命令的加密密碼。

+
** *《Dictionary》*
+
您可以新增所選字典項目的表格資料。dictionary項目屬性會選取要傳回的屬性。您可以在執行工作流程時選取單一值或多個值。例如、您可以選取單一磁碟區或多個磁碟區。預設會選取單一值。您也可以選取篩選規則。規則包含一個字典項目屬性、運算子和一個值。屬性也可以包含其參照的屬性。

+
例如、您可以指定集合體規則、列出名稱開頭為字串「aggr"的所有集合體、可用大小大於5 GB。群組中的第一條規則是屬性「name」、運算子「sharts with」和值aggr。同一群組的第二項規則是屬性「可用的_size_MB」、運算子為「>」、值為「5000」





下表列出可套用至使用者輸入類型的選項：

[cols="2*"]
|===
| 選項 | 說明 


 a| 
正在驗證
 a| 
您可以驗證使用者輸入類型、讓使用者只輸入有效值：

* 使用者輸入的字串和數字類型、可以使用工作流程執行期間所輸入的值進行驗證。
* 字串類型也可以使用規則運算式來驗證。
* 數字類型是數值浮點欄位、可使用指定的數值範圍進行驗證。




 a| 
鎖定值
 a| 
您可以鎖定查詢和列舉類型的值、以防止使用者覆寫下拉式值、並只啟用所顯示值的選取。



 a| 
標示為必填
 a| 
您可以將使用者輸入標記為必填、以便使用者必須輸入特定的使用者輸入、才能繼續執行工作流程。



 a| 
群組
 a| 
您可以群組相關的使用者輸入、並為使用者輸入群組提供名稱。群組可在使用者輸入對話方塊中展開及摺疊。您可以選取預設應展開的群組。



 a| 
應用條件
 a| 
有了條件式使用者輸入功能、您可以根據輸入給其他使用者輸入的值來設定使用者輸入的值。例如、在設定NAS傳輸協定的工作流程中、您可以將傳輸協定所需的使用者輸入指定為NFS、以啟用「讀取/寫入主機清單」使用者輸入。

|===